language: go
services:
  - docker
arch:
  - amd64
os: linux
dist: xenial
go:
- 1.16.x
deploy:
- provider: script
  on:
    tags: true
  script: bash ./deploy.sh
- provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file: bin/squid-exporter
  on:
    tags: true
