version: "3"
services:
  shinobi:
    image: registry.gitlab.com/shinobi-systems/shinobi:dev-arm64v8
    container_name: shinobi
    environment:
      - PLUGIN_KEYS={}
      - SSL_ENABLED=false
    volumes:
      - /home/pi/Shinobi/config:/config
      - /home/pi/Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
      - /home/pi/Shinobi/database:/var/lib/mysql
      - /home/pi/Shinobi/videos:/home/Shinobi/videos
      - /home/pi/Shinobi/plugins:/home/Shinobi/plugins
      - /dev/shm/Shinobi/streams:/dev/shm/streams
      - /mnt/sda1:/mnt/sda1
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/dri:/dev/dri
    ports:
      - 8088:8080
    restart: unless-stopped
    privileged: true

