server {
    listen 8920 ssl;
    listen [::]:8920 ssl;
    http2 on;

    include conf.d/psaghelyi_ssl_config;
    server_name psaghelyi.ddns.net;

    # Allow large attachments
    client_max_body_size 20M;

    location = / {
        return 301 https://$host:8920/web/;
    }

    location / {
        proxy_pass http://192.168.1.102:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_set_header X-Forwarded-Port 8920;
        proxy_set_header X-Forwarded-Ssl on;

        proxy_buffering off;
    }

    location = /web/ {
        proxy_pass http://192.168.1.102:8096/web/index.html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port 8920;
        proxy_set_header X-Forwarded-Ssl on;
    }

    location /socket {
        proxy_pass http://192.168.1.102:8096;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port 8920;
        proxy_set_header X-Forwarded-Ssl on;
    }
}

