version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    pid: host
    network_mode: host
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    restart: unless-stopped
    pid: host
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      - /dev/disk/:/dev/disk:ro        
    expose:
      - 8080
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    restart: unless-stopped
    command:
      - '-nginx.scrape-uri=http://host.docker.internal:88/stub_status'
    expose:
      - 9113
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./.prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - monitoring
    user: "${UID}:${GID}"
    depends_on:
      - node-exporter
      - cadvisor
      - nginx-exporter


  