{{- if .Values.serviceMonitor.rules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "squid-exporter.fullname" . }}
  labels:
    {{- include "squid-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "squid-exporter.fullname" . }}
      rules:
        {{- .Values.serviceMonitor.rules | toYaml | nindent 8 }}
{{- end }}