apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squid-exporter.fullname" . }}
  labels:
    {{- include "squid-exporter.labels" . | nindent 4 }}
data:
  SQUID_LOGIN: {{ .Values.squidConfig.login | b64enc }}
  SQUID_PASSWORD: {{ .Values.squidConfig.password | b64enc }}